export interface WorldwideTimeZone {
  name: string;
  country: string;
  value: string;
  aliases?: string[];
}

export const worldwideTimezones: WorldwideTimeZone[] = [
  // Middle East & Gulf
  { name: 'Riyadh', country: 'Saudi Arabia', value: 'Asia/Riyadh', aliases: ['saudia', 'saudi arabia', 'saudi', 'riyad'] },
  { name: 'Jeddah', country: 'Saudi Arabia', value: 'Asia/Riyadh', aliases: ['saudia', 'saudi arabia', 'saudi', 'jedah'] },
  { name: 'Dubai', country: 'United Arab Emirates', value: 'Asia/Dubai', aliases: ['uae', 'emirates', 'abu dhabi', 'dubay'] },
  { name: 'Doha', country: 'Qatar', value: 'Asia/Qatar', aliases: ['qatar'] },
  { name: 'Kuwait City', country: 'Kuwait', value: 'Asia/Kuwait', aliases: ['kuwait'] },
  { name: 'Muscat', country: 'Oman', value: 'Asia/Muscat', aliases: ['oman'] },
  { name: 'Manama', country: 'Bahrain', value: 'Asia/Bahrain', aliases: ['bahrain'] },
  { name: 'Jerusalem', country: 'Israel', value: 'Asia/Jerusalem', aliases: ['israel', 'tel aviv'] },
  { name: 'Amman', country: 'Jordan', value: 'Asia/Amman', aliases: ['jordan'] },
  { name: 'Beirut', country: 'Lebanon', value: 'Asia/Beirut', aliases: ['lebanon'] },
  { name: 'Damascus', country: 'Syria', value: 'Asia/Damascus', aliases: ['syria'] },
  { name: 'Baghdad', country: 'Iraq', value: 'Asia/Baghdad', aliases: ['iraq'] },
  { name: 'Tehran', country: 'Iran', value: 'Asia/Tehran', aliases: ['iran'] },

  // South Asia
  { name: 'Mumbai / New Delhi', country: 'India', value: 'Asia/Kolkata', aliases: ['india', 'bombay', 'calcutta', 'delhi', 'bangalore', 'kolkata'] },
  { name: 'Kolkata', country: 'India', value: 'Asia/Kolkata', aliases: ['india', 'calcutta'] },
  { name: 'Karachi', country: 'Pakistan', value: 'Asia/Karachi', aliases: ['pakistan', 'lahore', 'islamabad'] },
  { name: 'Dhaka', country: 'Bangladesh', value: 'Asia/Dhaka', aliases: ['bangladesh'] },
  { name: 'Colombo', country: 'Sri Lanka', value: 'Asia/Colombo', aliases: ['sri lanka', 'colombo'] },
  { name: 'Kathmandu', country: 'Nepal', value: 'Asia/Kathmandu', aliases: ['nepal'] },
  { name: 'Kabul', country: 'Afghanistan', value: 'Asia/Kabul', aliases: ['afghanistan'] },

  // East Asia
  { name: 'Tokyo', country: 'Japan', value: 'Asia/Tokyo', aliases: ['japan', 'kyoto', 'osaka'] },
  { name: 'Seoul', country: 'South Korea', value: 'Asia/Seoul', aliases: ['korea', 'south korea'] },
  { name: 'Shanghai', country: 'China', value: 'Asia/Shanghai', aliases: ['china', 'beijing', 'peking'] },
  { name: 'Hong Kong', country: 'Hong Kong (China)', value: 'Asia/Hong_Kong', aliases: ['hong kong', 'hk'] },
  { name: 'Taipei', country: 'Taiwan', value: 'Asia/Taipei', aliases: ['taiwan'] },
  { name: 'Ulaanbaatar', country: 'Mongolia', value: 'Asia/Ulaanbaatar', aliases: ['mongolia'] },

  // Southeast Asia
  { name: 'Singapore', country: 'Singapore', value: 'Asia/Singapore', aliases: ['singapore'] },
  { name: 'Kuala Lumpur', country: 'Malaysia', value: 'Asia/Kuala_Lumpur', aliases: ['malaysia', 'kl'] },
  { name: 'Bangkok', country: 'Thailand', value: 'Asia/Bangkok', aliases: ['thailand', 'phuket'] },
  { name: 'Jakarta', country: 'Indonesia', value: 'Asia/Jakarta', aliases: ['indonesia', 'bali', 'surabaya'] },
  { name: 'Ho Chi Minh City', country: 'Vietnam', value: 'Asia/Bangkok', aliases: ['vietnam', 'saigon', 'hanoi'] },
  { name: 'Manila', country: 'Philippines', value: 'Asia/Manila', aliases: ['philippines', 'manila'] },

  // Central Asia
  { name: 'Tashkent', country: 'Uzbekistan', value: 'Asia/Tashkent', aliases: ['uzbekistan'] },
  { name: 'Almaty', country: 'Kazakhstan', value: 'Asia/Almaty', aliases: ['kazakhstan'] },

  // Europe
  { name: 'London', country: 'United Kingdom', value: 'Europe/London', aliases: ['uk', 'gb', 'united kingdom', 'england', 'scotland', 'ireland'] },
  { name: 'Paris', country: 'France', value: 'Europe/Paris', aliases: ['france', 'french'] },
  { name: 'Berlin', country: 'Germany', value: 'Europe/Berlin', aliases: ['germany', 'deutschland', 'munich', 'frankfurt'] },
  { name: 'Rome', country: 'Italy', value: 'Europe/Rome', aliases: ['italy', 'rome', 'milan'] },
  { name: 'Madrid', country: 'Spain', value: 'Europe/Madrid', aliases: ['spain', 'barcelona'] },
  { name: 'Lisbon', country: 'Portugal', value: 'Europe/Lisbon', aliases: ['portugal'] },
  { name: 'Brussels', country: 'Belgium', value: 'Europe/Brussels', aliases: ['belgium'] },
  { name: 'Amsterdam', country: 'Netherlands', value: 'Europe/Amsterdam', aliases: ['holland', 'netherlands'] },
  { name: 'Zurich', country: 'Switzerland', value: 'Europe/Zurich', aliases: ['switzerland', 'geneva'] },
  { name: 'Vienna', country: 'Austria', value: 'Europe/Vienna', aliases: ['austria'] },
  { name: 'Athens', country: 'Greece', value: 'Europe/Athens', aliases: ['greece'] },
  { name: 'Moscow', country: 'Russia', value: 'Europe/Moscow', aliases: ['russia', 'moscow', 'st petersburg'] },
  { name: 'Kyiv', country: 'Ukraine', value: 'Europe/Kyiv', aliases: ['ukraine', 'kiev'] },
  { name: 'Warsaw', country: 'Poland', value: 'Europe/Warsaw', aliases: ['poland'] },
  { name: 'Prague', country: 'Czech Republic', value: 'Europe/Prague', aliases: ['czech'] },
  { name: 'Budapest', country: 'Hungary', value: 'Europe/Budapest', aliases: ['hungary'] },
  { name: 'Bucharest', country: 'Romania', value: 'Europe/Bucharest', aliases: ['romania'] },
  { name: 'Stockholm', country: 'Sweden', value: 'Europe/Stockholm', aliases: ['sweden'] },
  { name: 'Oslo', country: 'Norway', value: 'Europe/Oslo', aliases: ['norway'] },
  { name: 'Copenhagen', country: 'Denmark', value: 'Europe/Copenhagen', aliases: ['denmark'] },
  { name: 'Helsinki', country: 'Finland', value: 'Europe/Helsinki', aliases: ['finland'] },
  { name: 'Dublin', country: 'Ireland', value: 'Europe/Dublin', aliases: ['ireland'] },
  { name: 'Reykjavik', country: 'Iceland', value: 'Atlantic/Reykjavik', aliases: ['iceland'] },
  { name: 'Istanbul', country: 'Turkey', value: 'Europe/Istanbul', aliases: ['turkey', 'istanbul', 'ankara'] },

  // Americas (North)
  { name: 'New York', country: 'United States', value: 'America/New_York', aliases: ['us', 'usa', 'united states', 'east coast', 'ny'] },
  { name: 'Chicago', country: 'United States', value: 'America/Chicago', aliases: ['us', 'usa', 'united states', 'central', 'midwest'] },
  { name: 'Denver', country: 'United States', value: 'America/Denver', aliases: ['us', 'usa', 'united states', 'mountain'] },
  { name: 'Los Angeles', country: 'United States', value: 'America/Los_Angeles', aliases: ['us', 'usa', 'united states', 'west coast', 'california', 'la', 'pacific'] },
  { name: 'Phoenix', country: 'United States', value: 'America/Phoenix', aliases: ['us', 'usa', 'united states', 'arizona'] },
  { name: 'Anchorage', country: 'United States', value: 'America/Anchorage', aliases: ['us', 'usa', 'alaska'] },
  { name: 'Honolulu', country: 'United States', value: 'Pacific/Honolulu', aliases: ['us', 'usa', 'hawaii'] },
  { name: 'Toronto', country: 'Canada', value: 'America/Toronto', aliases: ['canada', 'ontario'] },
  { name: 'Vancouver', country: 'Canada', value: 'America/Vancouver', aliases: ['canada', 'bc', 'british columbia'] },
  { name: 'Montreal', country: 'Canada', value: 'America/Montreal', aliases: ['canada', 'quebec'] },
  { name: 'Calgary', country: 'Canada', value: 'America/Calgary', aliases: ['canada', 'alberta'] },
  { name: 'Winnipeg', country: 'Canada', value: 'America/Winnipeg', aliases: ['canada', 'manitoba'] },
  { name: 'Halifax', country: 'Canada', value: 'America/Halifax', aliases: ['canada', 'nova scotia'] },

  // Americas (Central & South)
  { name: 'Mexico City', country: 'Mexico', value: 'America/Mexico_City', aliases: ['mexico', 'cancun'] },
  { name: 'Bogota', country: 'Colombia', value: 'America/Bogota', aliases: ['colombia'] },
  { name: 'Lima', country: 'Peru', value: 'America/Lima', aliases: ['peru'] },
  { name: 'Santiago', country: 'Chile', value: 'America/Santiago', aliases: ['chile'] },
  { name: 'Sao Paulo', country: 'Brazil', value: 'America/Sao_Paulo', aliases: ['brazil', 'brasil', 'rio de janeiro'] },
  { name: 'Manaus', country: 'Brazil', value: 'America/Manaus', aliases: ['brazil', 'brasil', 'amazon'] },
  { name: 'Buenos Aires', country: 'Argentina', value: 'America/Buenos_Aires', aliases: ['argentina'] },
  { name: 'Caracas', country: 'Venezuela', value: 'America/Caracas', aliases: ['venezuela'] },
  { name: 'La Paz', country: 'Bolivia', value: 'America/La_Paz', aliases: ['bolivia'] },
  { name: 'Asuncion', country: 'Paraguay', value: 'America/Asuncion', aliases: ['paraguay'] },
  { name: 'Montevideo', country: 'Uruguay', value: 'America/Montevideo', aliases: ['uruguay'] },
  { name: 'Panama City', country: 'Panama', value: 'America/Panama', aliases: ['panama'] },
  { name: 'San Jose', country: 'Costa Rica', value: 'America/Costa_Rica', aliases: ['costa rica'] },
  { name: 'Havana', country: 'Cuba', value: 'America/Havana', aliases: ['cuba'] },
  { name: 'Kingston', country: 'Jamaica', value: 'America/Jamaica', aliases: ['jamaica'] },
  { name: 'Santo Domingo', country: 'Dominican Republic', value: 'America/Santo_Domingo', aliases: ['dominican republic'] },
  { name: 'San Juan', country: 'Puerto Rico', value: 'America/Puerto_Rico', aliases: ['puerto rico'] },
  { name: 'Nassau', country: 'Bahamas', value: 'America/Nassau', aliases: ['bahamas'] },
  { name: 'Quito', country: 'Ecuador', value: 'America/Quito', aliases: ['ecuador'] },

  // Africa
  { name: 'Cairo', country: 'Egypt', value: 'Africa/Cairo', aliases: ['egypt', 'cairo'] },
  { name: 'Johannesburg', country: 'South Africa', value: 'Africa/Johannesburg', aliases: ['south africa', 'cape town'] },
  { name: 'Nairobi', country: 'Kenya', value: 'Africa/Nairobi', aliases: ['kenya'] },
  { name: 'Lagos', country: 'Nigeria', value: 'Africa/Lagos', aliases: ['nigeria'] },
  { name: 'Casablanca', country: 'Morocco', value: 'Africa/Casablanca', aliases: ['morocco', 'rabat'] },
  { name: 'Algiers', country: 'Algeria', value: 'Africa/Algiers', aliases: ['algeria'] },
  { name: 'Tunis', country: 'Tunisia', value: 'Africa/Tunis', aliases: ['tunisia'] },
  { name: 'Tripoli', country: 'Libya', value: 'Africa/Tripoli', aliases: ['libya'] },
  { name: 'Addis Ababa', country: 'Ethiopia', value: 'Africa/Addis_Ababa', aliases: ['ethiopia'] },
  { name: 'Dar es Salaam', country: 'Tanzania', value: 'Africa/Dar_es_Salaam', aliases: ['tanzania'] },
  { name: 'Kampala', country: 'Uganda', value: 'Africa/Kampala', aliases: ['uganda'] },
  { name: 'Accra', country: 'Ghana', value: 'Africa/Accra', aliases: ['ghana'] },
  { name: 'Dakar', country: 'Senegal', value: 'Africa/Dakar', aliases: ['senegal'] },
  { name: 'Abidjan', country: 'Ivory Coast', value: 'Africa/Abidjan', aliases: ['ivory coast', 'cote d\'ivoire'] },
  { name: 'Luanda', country: 'Angola', value: 'Africa/Luanda', aliases: ['angola'] },
  { name: 'Khartoum', country: 'Sudan', value: 'Africa/Khartoum', aliases: ['sudan'] },
  { name: 'Harare', country: 'Zimbabwe', value: 'Africa/Harare', aliases: ['zimbabwe'] },
  { name: 'Lusaka', country: 'Zambia', value: 'Africa/Lusaka', aliases: ['zambia'] },
  { name: 'Douala', country: 'Cameroon', value: 'Africa/Douala', aliases: ['cameroon'] },
  { name: 'Antananarivo', country: 'Madagascar', value: 'Africa/Asmera', aliases: ['madagascar'] },

  // Oceania & Islands
  { name: 'Sydney', country: 'Australia', value: 'Australia/Sydney', aliases: ['australia', 'nsw'] },
  { name: 'Melbourne', country: 'Australia', value: 'Australia/Melbourne', aliases: ['australia', 'victoria'] },
  { name: 'Brisbane', country: 'Australia', value: 'Australia/Brisbane', aliases: ['australia', 'queensland'] },
  { name: 'Perth', country: 'Australia', value: 'Australia/Perth', aliases: ['australia', 'western australia'] },
  { name: 'Adelaide', country: 'Australia', value: 'Australia/Adelaide', aliases: ['australia', 'south australia'] },
  { name: 'Hobart', country: 'Australia', value: 'Australia/Hobart', aliases: ['australia', 'tasmania'] },
  { name: 'Darwin', country: 'Australia', value: 'Australia/Darwin', aliases: ['australia', 'northern territory'] },
  { name: 'Auckland', country: 'New Zealand', value: 'Pacific/Auckland', aliases: ['new zealand', 'nz', 'wellington'] },
  { name: 'Suva', country: 'Fiji', value: 'Pacific/Fiji', aliases: ['fiji'] },
  { name: 'Papeete', country: 'Tahiti', value: 'Pacific/Tahiti', aliases: ['tahiti', 'french polynesia'] },
  { name: 'Apia', country: 'Samoa', value: 'Pacific/Apia', aliases: ['samoa'] },
  { name: 'Port Louis', country: 'Mauritius', value: 'Indian/Mauritius', aliases: ['mauritius'] },
  { name: 'Male', country: 'Maldives', value: 'Indian/Maldives', aliases: ['maldives'] },
  { name: 'Victoria', country: 'Seychelles', value: 'Indian/Mahe', aliases: ['seychelles'] },
  { name: 'Hagatna', country: 'Guam', value: 'Pacific/Guam', aliases: ['guam'] },
  { name: 'Nuuk', country: 'Greenland', value: 'America/Nuuk', aliases: ['greenland'] }
];

export const countryBgs: Record<string, string> = {
  'default': 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1920&auto=format&fit=crop',
  'Pakistan': 'https://images.unsplash.com/photo-1627915591243-dbe6b4f74d08?q=80&w=1920&auto=format&fit=crop',
  'Saudi Arabia': 'https://images.unsplash.com/photo-1586724230073-50950b8c7ae2?q=80&w=1920&auto=format&fit=crop',
  'United Arab Emirates': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1920&auto=format&fit=crop',
  'United Kingdom': 'https://images.unsplash.com/photo-1513635269975-59663e0ca1ad?q=80&w=1920&auto=format&fit=crop',
  'United States': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=1920&auto=format&fit=crop',
  'Japan': 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1920&auto=format&fit=crop',
  'Australia': 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=1920&auto=format&fit=crop',
  'France': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1920&auto=format&fit=crop',
  'Germany': 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?q=80&w=1920&auto=format&fit=crop',
  'Egypt': 'https://images.unsplash.com/photo-1503177119275-0aa32b31d468?q=80&w=1920&auto=format&fit=crop',
  'Russia': 'https://images.unsplash.com/photo-1512495039889-52a3b799c9bc?q=80&w=1920&auto=format&fit=crop',
  'Singapore': 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1920&auto=format&fit=crop',
  'Canada': 'https://images.unsplash.com/photo-1485081661445-51c367f2e67d?q=80&w=1920&auto=format&fit=crop',
  'Brazil': 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?q=80&w=1920&auto=format&fit=crop',
  'China': 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?q=80&w=1920&auto=format&fit=crop',
  'South Korea': 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1920&auto=format&fit=crop',
  'India': 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=1920&auto=format&fit=crop',
  'Italy': 'https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?q=80&w=1920&auto=format&fit=crop',
  'Spain': 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?q=80&w=1920&auto=format&fit=crop',
  'Switzerland': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1920&auto=format&fit=crop',
  'Netherlands': 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1920&auto=format&fit=crop',
  'Turkey': 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?q=80&w=1920&auto=format&fit=crop',
  'Mexico': 'https://images.unsplash.com/photo-1512813583145-baaa340ef29f?q=80&w=1920&auto=format&fit=crop',
  'Thailand': 'https://images.unsplash.com/photo-1528181304800-2f12585c83e7?q=80&w=1920&auto=format&fit=crop',
  'Malaysia': 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?q=80&w=1920&auto=format&fit=crop',
  'Indonesia': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=1920&auto=format&fit=crop',
  'Vietnam': 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=1920&auto=format&fit=crop',
  'Philippines': 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?q=80&w=1920&auto=format&fit=crop',
  'South Africa': 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?q=80&w=1920&auto=format&fit=crop',
  'New Zealand': 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=1920&auto=format&fit=crop',
  'Maldives': 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1920&auto=format&fit=crop',

  // Regional/Generic Fallbacks for All Other Countries
  'middle-east': 'https://images.unsplash.com/photo-1547989453-11e67ffb3885?q=80&w=1920&auto=format&fit=crop',
  'europe': 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=1920&auto=format&fit=crop',
  'asia': 'https://images.unsplash.com/photo-1480796927426-f609979314bd?q=80&w=1920&auto=format&fit=crop',
  'africa': 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?q=80&w=1920&auto=format&fit=crop',
  'latin-america': 'https://images.unsplash.com/photo-1585464231473-d36d1b294aa9?q=80&w=1920&auto=format&fit=crop',
  'pacific': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1920&auto=format&fit=crop',
};

